name: Charlex CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  MIX_ENV: test
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
jobs:
   
  test:
    
    name: run tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        elixir: [1.10.3]
        otp: [22.3]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir }} # Define the elixir version [required]
        otp-version: ${{ matrix.otp }} # Define the OTP version [required]


    - name: Restore dependencies cache
      uses: actions/cache@v2
      id: mix-cache
      with:
        path: deps
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
        
    - name: Install dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Run tests
      run: mix test
    
   
    
  deploy:
    needs: [test]

    name: Deploy on Gigalixir
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: git remote add gigalixir https://${{ secrets.GIGALIXIR_EMAIL }}:${{ secrets.GIGALIXIR_API_KEY }}@git.gigalixir.com/${{secrets.GIGALIXIR_APP}}.git
    - run: git -c http.extraheader="GIGALIXIR-HOT:true" push -f gigalixir master
